### ISSUE TITLE
Filter user folders and drafts and templates

### ISSUE THREAD

**Issue by blankdots** [CSCfi/metadata-submitter-frontend#423]
#### Description

As a user that has many folders, drafts and template i would need to filter them so i can find what i am looking for.

Add to folders, drafts and templates search by name and date created

![image](https://user-images.githubusercontent.com/47524/129313202-58a26983-1abb-41c5-ac26-897154560065.png)

`dateCreated` key already exists in folder but maybe this might need some additional help from back-end to do the search.

#### DoD (Definition of Done)

user is able to filter by name and by date created

#### Testing

unit and integration testing

**Comment by blankdots** [comment]
i will take care of this in the backend

**Comment by genie9** [comment]
@blankdots Some questions have arisen during the implementation of folder filtering by name:
1. Should there be an additional field for searching `text_name` separating folder name by delimiters?
    - discussed in RC => yes
2. Is it good enough to search by full string matching with text search (indexed)?
or
3. Should we implement regex with ^-prefix-  so we could use partial and also indexed search?
    - discussed in RC => 2 is chosen
4. Would name filtering be using only one word, not an array of words?
5. Should `description`-field be included in the search (indexed)? How long are descriptions usually and would it mess filtering by name? (Asking because Stefan's example included `description`-field in indexing)
6. Should the new field `text_name` be shown in the query results?

**Comment by blankdots** [comment]
i assume we are talking about this backend issue CSCfi/metadata-submitter/issues/280
> @blankdots Some questions have arisen during the implementation of folder filtering by name:
> 
>     1. Should there be an additional field for searching `text_name` separating folder name by delimiters?
>        
>        * discussed in RC => yes

true, but that is an implementation detail.

>     2. Is it good enough to search by full string matching with text search (indexed)?

yes, text search should be it, we will not do regex, to take advantage of indexing. Simple search, we will no do anything fancy like elastic search does.

>     3. Should we implement regex with ^-prefix-  so we could use partial and also indexed search?
>        
>        * discussed in RC => 2 is chosen
> 
No regex please, it is not required for this use case.

>     4. Would name filtering be using only one word, not an array of words?

based on this, if there are multiple words https://docs.mongodb.com/manual/text-search/#-text-operator will create an `OR` so we can get as many words as needed

>     5. Should `description`-field be included in the search (indexed)? How long are descriptions usually and would it mess filtering by name? (Asking because Stefan's example included `description`-field in indexing)
> 

This I am not 100% sure, but I would leave out, as descriptions can often take the form of an abstract. If we get request to do it then we will add it with another issue.

>     6. Should the new field `text_name` be shown in the query results?
No. that is internal

**Comment by genie9** [comment]
`i assume we are talking about this backend issue CSCfi/metadata-submitter/issues/280`

Sorry, was in the wrong repository, should this be copied to backend
