### ISSUE TITLE
Implement (auto-)saving draft versions of folders

### ISSUE THREAD

**Issue by otahontas** [CSCfi/metadata-submitter-frontend#67]
#### Proposed solution

If user currently changes away from form, alert is shown asking if user want's to save the form. Save doesn't do anything, so implement draft possibility. 

User should also be notified somehow that they have non-finished versions of forms available. 

In best case form is auto-saved every now and then and saving is reported to user via notification.

#### DoD (Definition of Done)

Saving draft versions is possible.

**Comment by saulipurhonen** [comment]
I'm wondering what information we want to save into drafts.
For now the logical data would be accessionId and schema. To get that data, we need to use createFromJSON or createFromXML methods. 
However if user hasn't filled required fields but wants to save form as an draft, createFromJSON method doesn't work since submission doesn't validate.

Example response from Study/form (user has filled only Study Description field):

data:
  detail: "Provided input does not seem correct because: ''descriptor' is a required property'"
  instance: "/objects/study"
  title: "Bad Request"

Example does work when required fields are filled.

Does it make sense that user needs to fill required fields before being able to save a draft?

Any ideas @blankdots, @csc-jm ?

**Comment by saulipurhonen** [comment]
Pending on draft validation changes in back-end.

**Comment by blankdots** [comment]
this would be solved with https://github.com/CSCfi/metadata-submitter/issues/158
